# Netlify CMS設定ファイル

backend:
  name: git-gateway
  branch: main # GitHubのブランチ

# 編集内容をプレビューするためのローカルサーバー設定
local_backend: true

# メディアファイルのアップロード先
media_folder: "images"
public_folder: "/images"

# コレクション定義
collections:
  - name: "news"
    label: "新着情報"
    folder: "_posts/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "投稿日", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "内容", name: "content", widget: "markdown"}
      - label: "画像"
        name: "images"
        widget: "list"
        required: false
        fields:
          - {label: "画像", name: "path", widget: "image"}
          - {label: "幅", name: "width", widget: "number", default: 400}
          - {label: "高さ", name: "height", widget: "number", default: 300}
      - {label: "YouTubeリンク", name: "youtube", widget: "string", required: false}
      - {label: "HTMLを使用", name: "useHtml", widget: "boolean", default: false}

  - name: "pages"
    label: "固定ページ"
    files:
      - file: "aboutus.html"
        label: "連絡協議会について"
        name: "aboutus"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}
      - file: "event.html"
        label: "イベント"
        name: "event"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}
      - file: "team.html"
        label: "参加団体"
        name: "team"
        fields:
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}
