name: Build News Data

on:
  push:
    branches: [ main, master ]
    paths:
      - '_posts/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - '_posts/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build news data
      run: npm run build-all

    - name: Commit and push changes
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add posts-list.json data/topics.json
        if ! git diff --staged --quiet; then
          git commit -m "Auto-build news data [skip ci]"
          git push origin HEAD:${{ github.ref_name }}
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 